<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Venv on hnakamur&#39;s blog</title>
    <link>https://hnakamur.github.io/blog/tags/venv/</link>
    <description>Recent content in Venv on hnakamur&#39;s blog</description>
    <generator>Hugo</generator>
    <language>ja-jp</language>
    <lastBuildDate>Sat, 25 Feb 2017 00:45:00 +0900</lastBuildDate>
    <atom:link href="https://hnakamur.github.io/blog/tags/venv/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>CentOS 7のepelでインストールしたpython3.4でvenvを使うとエラーになる件の回避策</title>
      <link>https://hnakamur.github.io/blog/2017/02/25/workaround-for-epel-python3.4-venv-on-centos7/</link>
      <pubDate>Sat, 25 Feb 2017 00:45:00 +0900</pubDate>
      <guid>https://hnakamur.github.io/blog/2017/02/25/workaround-for-epel-python3.4-venv-on-centos7/</guid>
      <description>&lt;h2 id=&#34;はじめに&#34;&gt;はじめに&lt;/h2&gt;&#xA;&lt;p&gt;CentOS 7のpythonパッケージは2.7.xなので、3系を使うには別途インストールする必要があります。&#xA;EPELの &lt;a href=&#34;https://f-o.org.uk/2016/python3-centos-and-pip.html&#34;&gt;&lt;code&gt;python34`` パッケージを使うと ``python3 -m venv venv`` でエラーになるという問題が起きたのですが、 &lt;/code&gt;Floating Octothorpe: Python3, CentOS and pip&lt;/a&gt; の記事で解決したのでメモです。&lt;/p&gt;</description>
    </item>
  </channel>
</rss>
