<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja-jp" lang="ja-jp">
<head>
  <link href="https://gmpg.org/xfn/11" rel="profile">
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="generator" content="Hugo 0.111.2">

  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>CentOS 7のepelでインストールしたpython3.4でvenvを使うとエラーになる件の回避策 &middot; hnakamur&#39;s blog</title>
  <meta name="description" content="" />

  
  <link type="text/css" rel="stylesheet" href="https://hnakamur.github.io/blog/css/print.css" media="print">
  <link type="text/css" rel="stylesheet" href="https://hnakamur.github.io/blog/css/poole.css">
  <link type="text/css" rel="stylesheet" href="https://hnakamur.github.io/blog/css/syntax.css">
  <link type="text/css" rel="stylesheet" href="https://hnakamur.github.io/blog/css/copy-button.css">
  <link type="text/css" rel="stylesheet" href="https://hnakamur.github.io/blog/css/hyde.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Abril+Fatface|PT+Sans:400,400i,700">


  
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="https://hnakamur.github.io/blog/apple-touch-icon-144-precomposed.png">
  <link rel="shortcut icon" href="https://hnakamur.github.io/blog/favicon.png">

  
  


<script async src="https://www.googletagmanager.com/gtag/js?id=G-KMMXGG2Z56"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-KMMXGG2Z56');
</script>



</head>

  <body class=" ">
  <aside class="sidebar">
  <div class="container sidebar-sticky">
    <div class="sidebar-about">
      <a href="https://hnakamur.github.io/blog/"><h1>hnakamur&#39;s blog</h1></a>
      <p class="lead">
       my tech memo 
      </p>
    </div>

    <nav>
      <ul class="sidebar-nav">
        <li><a href="https://hnakamur.github.io/blog/"> blog home </a></li><li><a href="https://github.com/hnakamur"> github @hnakamur </a></li><li><a href="https://twitter.com/hnakamur2"> twitter @hnakamur2 </a></li>
      </ul>
    </nav>

    <p>powered by <a href="http://gohugo.io">Hugo</a> and <a href="https://pages.github.com/">GitHub Pages</a></p>
    <p>&copy; 2023. All rights reserved. </p>
  </div>
</aside>

    <main class="content container">
    <div class="post">
  <h1>CentOS 7のepelでインストールしたpython3.4でvenvを使うとエラーになる件の回避策</h1>
  <time datetime=2017-02-25T00:45:00&#43;0900 class="post-date">2017-02-25</time>
  <nav id="TableOfContents">
  <ul>
    <li><a href="#はじめに">はじめに</a></li>
    <li><a href="#ius-community-repo-のpython-36x">IUS Community Repo のPython 3.6.x</a></li>
    <li><a href="#extra-packages-for-enterprise-linux-epelのpython-34x">Extra Packages for Enterprise Linux (EPEL)のPython 3.4.x</a></li>
    <li><a href="#epelのpython-34でvenvを使うとエラー">EPELのPython 3.4でvenvを使うとエラー</a></li>
    <li><a href="#epelのpython-34でvenvを使うための回避策">EPELのPython 3.4でvenvを使うための回避策</a></li>
  </ul>
</nav>
  <h2 id="はじめに">はじめに</h2>
<p>CentOS 7のpythonパッケージは2.7.xなので、3系を使うには別途インストールする必要があります。
EPELの <a href="https://f-o.org.uk/2016/python3-centos-and-pip.html"><code>python34`` パッケージを使うと ``python3 -m venv venv`` でエラーになるという問題が起きたのですが、 </code>Floating Octothorpe: Python3, CentOS and pip</a> の記事で解決したのでメモです。</p>
<h2 id="ius-community-repo-のpython-36x">IUS Community Repo のPython 3.6.x</h2>
<p><a href="https://wiki.centos.org/AdditionalResources/Repositories">AdditionalResources/Repositories - CentOS Wiki</a> の <a href="https://ius.io/">IUS Community Repo</a> なら <code>python36u</code> というパッケージ名でPython 3.6.xがインストールできます。
<a href="https://github.com/iuscommunity-pkg?utf8=%E2%9C%93&amp;q=python36u&amp;type=&amp;language=">IUS Community Project Packages</a> を見ると他に <code>python36u-setuptools</code>, <code>uwsgi-plugin-python36u</code>, <code>python36u-pip</code>, <code>python36u-lxml</code>, <code>python36u-psycopg2</code> パッケージが提供されています。</p>
<p>こちらは <code>python3.6 -m venv venv</code> で問題なくvirtualenv環境が作成できました。</p>
<h2 id="extra-packages-for-enterprise-linux-epelのpython-34x">Extra Packages for Enterprise Linux (EPEL)のPython 3.4.x</h2>
<p>EPELでも <code>python34</code> というパッケージ名でPython 3.4.xがインストールできます。 IUS Community Repoの3.6.xよりは古いですが、 <code>python34-*</code> のパッケージはこちらのほうが多いです（とは言え <code>venv</code> を使うのであればあまり関係無いとも言えますが）。
また、EPELは他でも使うので私は常に有効にしています。
サードパーティのレポジトリの種類はなるべく限定しておきたいと考えるとIUS Community Repoは使わずにEPELの <code>python34</code> を使うという選択肢もありえます。</p>
<h2 id="epelのpython-34でvenvを使うとエラー">EPELのPython 3.4でvenvを使うとエラー</h2>
<p><code>python3.4 -m venv venv</code> を実行すると以下のようなエラーが出ました（ここでは <code>/home/admin/blog</code> というディレクトリで実行しました）。</p>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-console" data-lang="console"><span class="line"><span class="cl"><span class="gp">$</span> python3.4 -m venv venv
</span></span><span class="line"><span class="cl"><span class="go">Error: Command &#39;[&#39;/home/admin/blog/venv/bin/python3.4&#39;, &#39;-Im&#39;, &#39;ensurepip&#39;, &#39;--upgrade&#39;, &#39;--default-pip&#39;]&#39; returned non-zero exit status 1
</span></span></span></code></pre></div><p>エラーになったコマンドを直接実行すると <code>/usr/lib64/python3.4/ensurepip/_bundled/setuptools-20.10.1-py2.py3-none-any.whl</code> というファイルが無くてエラーになっていることがわかります。</p>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-console" data-lang="console"><span class="line"><span class="cl"><span class="gp">$</span> /home/admin/blog/venv/bin/python3.4 -Im ensurepip --upgrade --default-pip
</span></span><span class="line"><span class="cl"><span class="go">Traceback (most recent call last):
</span></span></span><span class="line"><span class="cl"><span class="go">  File &#34;/usr/lib64/python3.4/runpy.py&#34;, line 170, in _run_module_as_main
</span></span></span><span class="line"><span class="cl"><span class="go">    &#34;__main__&#34;, mod_spec)
</span></span></span><span class="line"><span class="cl"><span class="go">  File &#34;/usr/lib64/python3.4/runpy.py&#34;, line 85, in _run_code
</span></span></span><span class="line"><span class="cl"><span class="go">    exec(code, run_globals)
</span></span></span><span class="line"><span class="cl"><span class="go">  File &#34;/usr/lib64/python3.4/ensurepip/__main__.py&#34;, line 4, in &lt;module&gt;
</span></span></span><span class="line"><span class="cl"><span class="go">    ensurepip._main()
</span></span></span><span class="line"><span class="cl"><span class="go">  File &#34;/usr/lib64/python3.4/ensurepip/__init__.py&#34;, line 209, in _main
</span></span></span><span class="line"><span class="cl"><span class="go">    default_pip=args.default_pip,
</span></span></span><span class="line"><span class="cl"><span class="go">  File &#34;/usr/lib64/python3.4/ensurepip/__init__.py&#34;, line 98, in bootstrap
</span></span></span><span class="line"><span class="cl"><span class="go">    &#34;_bundled/{}&#34;.format(wheel_name),
</span></span></span><span class="line"><span class="cl"><span class="go">  File &#34;/usr/lib64/python3.4/pkgutil.py&#34;, line 629, in get_data
</span></span></span><span class="line"><span class="cl"><span class="go">    return loader.get_data(resource_name)
</span></span></span><span class="line"><span class="cl"><span class="go">  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 1623, in get_data
</span></span></span><span class="line"><span class="cl"><span class="go">FileNotFoundError: [Errno 2] No such file or directory: &#39;/usr/lib64/python3.4/ensurepip/_bundled/setuptools-20.10.1-py2.py3-none-any.whl&#39;
</span></span></span></code></pre></div><p>この問題は
<a href="https://bugzilla.redhat.com/show_bug.cgi?id=1263057">Bug 1263057 – pyvenv3.4 doesn&rsquo;t work without pip</a>
に報告されています。</p>
<h2 id="epelのpython-34でvenvを使うための回避策">EPELのPython 3.4でvenvを使うための回避策</h2>
<p>EPELのインストールからのコマンドをまとめると以下のようになります。</p>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-console" data-lang="console"><span class="line"><span class="cl"><span class="go">sudo yum install epel-release
</span></span></span><span class="line"><span class="cl"><span class="go">sudo yum install python34 python34-setuptools python34-pip
</span></span></span><span class="line"><span class="cl"><span class="go">sudo mkdir -p /usr/lib64/python3.4/ensurepip/_bundled
</span></span></span><span class="line"><span class="cl"><span class="go">sudo curl -o /usr/lib64/python3.4/ensurepip/_bundled/setuptools-20.10.1-py2.py3-none-any.whl \
</span></span></span><span class="line"><span class="cl"><span class="go">    https://pypi.python.org/packages/c5/e2/72d706eeda837564b9fecdc8b2bf48b33467ae928ed05d4ac157463c90fb/setuptools-20.10.1-py2.py3-none-any.whl
</span></span></span><span class="line"><span class="cl"><span class="go">sudo curl -o /usr/lib64/python3.4/ensurepip/_bundled/pip-8.1.1-py2.py3-none-any.whl \
</span></span></span><span class="line"><span class="cl"><span class="go">    https://pypi.python.org/packages/31/6a/0f19a7edef6c8e5065f4346137cc2a08e22e141942d66af2e1e72d851462/pip-8.1.1-py2.py3-none-any.whl
</span></span></span></code></pre></div><p><a href="https://f-o.org.uk/2016/python3-centos-and-pip.html">Floating Octothorpe: Python3, CentOS and pip</a> に詳しく書かれていますが、
上記の <code>setuptools</code> と <code>pip</code> のバージョンは <code>/usr/lib64/python3.4/ensurepip/__init__.py</code> に書いてあるバージョンに一致させる必要があります。</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt">11
</span><span class="lnt">12
</span><span class="lnt">13
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-python" data-lang="python"><span class="line"><span class="cl"><span class="n">_SETUPTOOLS_VERSION</span> <span class="o">=</span> <span class="s2">&#34;20.10.1&#34;</span>
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl"><span class="n">_PIP_VERSION</span> <span class="o">=</span> <span class="s2">&#34;8.1.1&#34;</span>
</span></span></code></pre></td></tr></table>
</div>
</div>
</div>


<script src="https://hnakamur.github.io/blog/js/copy-button.js"></script>
    </main>

    
<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
	ga('create', 'G-KMMXGG2Z56', 'auto');
	
	ga('send', 'pageview');
}
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>

  </body>
</html>
